version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: client_db
      MYSQL_USER: client_user
      MYSQL_PASSWORD: vNrCxPoiXcjijx39bcuBVDiw

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: client_user
      WORDPRESS_DB_PASSWORD: vNrCxPoiXcjijx39bcuBVDiw
      WORDPRESS_DB_NAME: client_db
      WORDPRESS_TABLE_PREFIX: tiger_
    working_dir: /var/www/html
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./_dev/apache2:/etc/apache2
volumes:
    db_data: {}